-- ============================================================
-- SQL SCRIPT: CREATE shareholder_payment_methods TABLE
-- Run this in your Supabase SQL Editor.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.shareholder_payment_methods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shareholder_id BIGINT NOT NULL REFERENCES public.shareholders(id) ON DELETE CASCADE,
  payment_type TEXT NOT NULL CHECK (payment_type IN ('zelle', 'cashapp', 'check')),
  account_handle TEXT,
  account_number TEXT,
  account_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT shareholder_payment_methods_shareholder_id_key UNIQUE (shareholder_id)
);

-- Index for quick lookups by shareholder_id
CREATE INDEX IF NOT EXISTS idx_shareholder_payment_methods_shareholder_id
  ON public.shareholder_payment_methods(shareholder_id);

-- Enable Row Level Security
ALTER TABLE public.shareholder_payment_methods ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to view their own payment method
CREATE POLICY "Users can view own payment method"
  ON public.shareholder_payment_methods
  FOR SELECT
  TO authenticated
  USING (true);

-- Allow authenticated users to insert their own payment method
CREATE POLICY "Users can insert own payment method"
  ON public.shareholder_payment_methods
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Allow authenticated users to update their own payment method
CREATE POLICY "Users can update own payment method"
  ON public.shareholder_payment_methods
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Grant access to service_role and authenticated
GRANT ALL ON TABLE public.shareholder_payment_methods TO service_role;
GRANT ALL ON TABLE public.shareholder_payment_methods TO authenticated;
GRANT ALL ON SEQUENCE public.shareholder_payment_methods_id_seq TO service_role;
GRANT ALL ON SEQUENCE public.shareholder_payment_methods_id_seq TO authenticated;
