-- ============================================================
-- SQL SCRIPT: CREATE legacy_shareholders STAGING TABLE
-- Run this in your Supabase SQL Editor.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.legacy_shareholders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Shareholder Identity
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  telephone TEXT,
  nationality TEXT,
  
  -- Investment Portfolio Details (Single & Multiple Allocations)
  opportunity_id BIGINT REFERENCES public.opportunities(id) ON DELETE SET NULL,
  amount_invested NUMERIC NOT NULL DEFAULT 0,
  start_date DATE DEFAULT CURRENT_DATE,
  investments JSONB DEFAULT '[]'::jsonb,
  
  -- Payout / Payment Method Details
  payment_type TEXT CHECK (payment_type IN ('zelle', 'cashapp', 'check', 'none')),
  account_handle TEXT,
  account_number TEXT,
  account_name TEXT,
  
  -- Claim / Sync Status
  is_claimed BOOLEAN DEFAULT FALSE,
  claimed_at TIMESTAMPTZ,
  claimed_by_shareholder_id BIGINT REFERENCES public.shareholders(id) ON DELETE SET NULL,
  
  -- Administrative Metadata
  notes TEXT,
  created_by_admin_id UUID REFERENCES public.admins(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure multiple investments column exists on existing installations
ALTER TABLE public.legacy_shareholders 
  ADD COLUMN IF NOT EXISTS investments JSONB DEFAULT '[]'::jsonb;

-- Index for instant lookup on sign-in
CREATE INDEX IF NOT EXISTS idx_legacy_shareholders_email 
  ON public.legacy_shareholders(LOWER(email));

-- Enable Row Level Security
ALTER TABLE public.legacy_shareholders ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users / service role access
CREATE POLICY "Admin full access to legacy_shareholders"
  ON public.legacy_shareholders
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT ALL ON TABLE public.legacy_shareholders TO service_role;
GRANT ALL ON TABLE public.legacy_shareholders TO authenticated;
GRANT ALL ON SEQUENCE public.legacy_shareholders_id_seq TO service_role;
GRANT ALL ON SEQUENCE public.legacy_shareholders_id_seq TO authenticated;
