-- 1. Create the `opportunity_valuations` table (acts as the source of truth for NAV)
CREATE TABLE IF NOT EXISTS public.opportunity_valuations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id BIGINT NOT NULL, -- You can add REFERENCES public.opportunities(id) if needed
  total_asset_value NUMERIC NOT NULL,
  valuation_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_by_admin_id UUID,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create the `investment_valuations` table (stores the calculated individual performances)
CREATE TABLE IF NOT EXISTS public.investment_valuations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  investment_id BIGINT NOT NULL,
  shareholder_id BIGINT NOT NULL,
  opportunity_id BIGINT NOT NULL,
  current_value NUMERIC NOT NULL,
  valuation_date DATE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Optional: Add a helper column to investments table so it's super easy to fetch the current value
ALTER TABLE public.investments 
ADD COLUMN IF NOT EXISTS current_value NUMERIC;

-- 3. Create the Database Function that does the math
CREATE OR REPLACE FUNCTION public.update_investment_valuations()
RETURNS TRIGGER AS $$
DECLARE
    v_total_capital NUMERIC;
    v_investment RECORD;
    v_new_value NUMERIC;
BEGIN
    -- Step A: Calculate the total initial capital raised for the opportunity
    SELECT COALESCE(SUM(amount_invested), 0)
    INTO v_total_capital
    FROM public.investments
    WHERE opportunity_id = NEW.opportunity_id;

    -- Step B: Prevent division by zero if there are no investments yet
    IF v_total_capital > 0 THEN
        -- Step C: Loop through each investment for this opportunity
        FOR v_investment IN 
            SELECT id, shareholder_id, amount_invested 
            FROM public.investments 
            WHERE opportunity_id = NEW.opportunity_id
        LOOP
            -- Step D: Calculate the new proportional value for this specific user
            v_new_value := (v_investment.amount_invested / v_total_capital) * NEW.total_asset_value;

            -- Step E: Insert a new historical record into the investment_valuations table
            INSERT INTO public.investment_valuations (
                investment_id, 
                shareholder_id, 
                opportunity_id, 
                current_value, 
                valuation_date
            ) VALUES (
                v_investment.id,
                v_investment.shareholder_id,
                NEW.opportunity_id,
                v_new_value,
                NEW.valuation_date
            );
            
            -- Step F (Bonus): Update the `current_value` column on the main investments table 
            -- so your frontend can just read `investment.current_value` without doing a JOIN
            UPDATE public.investments 
            SET current_value = v_new_value 
            WHERE id = v_investment.id;
            
        END LOOP;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Attach the Trigger to the opportunity_valuations table
DROP TRIGGER IF EXISTS trigger_update_investment_valuations ON public.opportunity_valuations;

CREATE TRIGGER trigger_update_investment_valuations
AFTER INSERT OR UPDATE OF total_asset_value ON public.opportunity_valuations
FOR EACH ROW
EXECUTE FUNCTION public.update_investment_valuations();
