-- ============================================================
-- SQL MIGRATION: OPERATING EXPENSES TABLE
-- ============================================================
-- Run this in your Supabase SQL Editor to track actual operating
-- expenses and disbursements for WINAM Core Portfolio Equity and funds.

CREATE TABLE IF NOT EXISTS public.operating_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  category TEXT NOT NULL CHECK (
    category IN (
      'Payment Processing',
      'Legal & Professional',
      'Fund Administration',
      'Technology & Software',
      'Marketing & Compliance',
      'Other Operating'
    )
  ),
  description TEXT NOT NULL,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
  vendor TEXT,
  opportunity_id BIGINT REFERENCES public.opportunities(id) ON DELETE SET NULL,
  payment_method TEXT DEFAULT 'Card',
  receipt_url TEXT,
  created_by TEXT
);

-- Optimal Indexes for date and opportunity filtering
CREATE INDEX IF NOT EXISTS idx_operating_expenses_opp_date 
  ON public.operating_expenses(opportunity_id, expense_date);

CREATE INDEX IF NOT EXISTS idx_operating_expenses_category 
  ON public.operating_expenses(category);

-- Sample Initial Actual Expenses for Core Portfolio Equity (Opportunity #9)
-- (You can customize or remove these as needed)
INSERT INTO public.operating_expenses (expense_date, category, description, amount, vendor, opportunity_id, payment_method)
VALUES
  ('2026-09-02', 'Payment Processing', 'Stripe Merchant Processing & Gateway Fees (Batch 1)', 58.30, 'Stripe Inc.', 9, 'Card'),
  ('2026-09-05', 'Legal & Professional', 'Corporate Governance & Annual Franchise Tax Filing', 300.00, 'State Department of State', 9, 'Wire'),
  ('2026-09-10', 'Technology & Software', 'Cloud Hosting, Vault Security & Audit Infrastructure', 150.00, 'Vercel / Supabase Platform', 9, 'Card')
ON CONFLICT DO NOTHING;
